site_name: Archiverse Theia
site_description: Archiverse Theia, house of Archi
repo_url: https://github.com/ntrtd/archiverse-archie

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.highlight
    - search.suggest
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - footnotes
  - attr_list
  - md_in_html

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@11.5.0/dist/mermaid.min.js

nav:
  - Home: index.md # Corresponds to docs/README.md (MkDocs uses index.md by default for root)
  - Architecture:
    - Overview: architecture/index.md
    - Backend Extensions: architecture/backend-extensions.md
    - Frontend Extensions: architecture/frontend-extensions.md
  - Features:
    - Virtual Filesystem: features/virtual-filesystem.md
    - GLSP Diagramming: features/glsp-diagramming.md
    - LLM Integration: features/llm-integration.md
    - Form Editing: features/form-editing.md
    - Multi-Grammar Handling: features/multi-grammar-handling.md
  - AI:
    - Introduction: ai/index.md
    - Architecture: ai/architecture.md
    - Archiverse Intelligence: ai/archiverse-intelligence.md
    - User Experience: ai/user-experience.md
  - Scenarios:
    - Import, Review, Export: scenarios/import-review-export.md
    - ERP upgrade: scenarios/hybrid-ea-ingestion.md
  - Development:
    - Setup: development/setup.md
